# Generated by Django 4.0.2 on 2022-02-27 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apprestapp1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='nombre',
            field=models.CharField(max_length=40, verbose_name='nombre_restaurant'),
        ),
    ]
