# Generated by Django 4.0.2 on 2022-02-27 17:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Apprestapp1', '0002_alter_restaurant_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='categoria',
            field=models.CharField(default=datetime.datetime(2022, 2, 27, 17, 57, 47, 455018, tzinfo=utc), max_length=50, verbose_name='categoria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='fecha',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='informacion',
            field=models.CharField(default=datetime.datetime(2022, 2, 27, 17, 58, 13, 727001, tzinfo=utc), max_length=1000, verbose_name='informacion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='propietario',
            field=models.CharField(default=datetime.datetime(2022, 2, 27, 17, 58, 20, 503246, tzinfo=utc), max_length=40, verbose_name='propietario'),
            preserve_default=False,
        ),
    ]
