# Generated by Django 4.0.2 on 2022-02-27 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apprestapp1', '0003_restaurant_categoria_restaurant_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='fecha',
            field=models.DateField(auto_now_add=True, verbose_name='fecha'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='nombre',
            field=models.CharField(max_length=40, verbose_name='nombre'),
        ),
    ]
