# Generated by Django 4.0.2 on 2022-02-28 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apprestapp1', '0004_alter_restaurant_fecha_alter_restaurant_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='imagen',
            field=models.ImageField(blank=True, default='placeholder.png', null=True, upload_to='imagenes'),
        ),
    ]
